### ISSUE TITLE
Pause on unfocus

### ISSUE THREAD

**Issue by TackerTacker** [pycbouh/godot-time-tracker#2]
Thank you for making this tool, I really like it. It is nice and simple, just click start and you are tracking your time. 
I just wish the timer would pause when Godot loses focus, would it be possible to add this feature? 
It would be awesome if that is possible.

**Comment by pycbouh** [comment]
I'm glad you like it!

> I just wish the timer would pause when Godot loses focus, would it be possible to add this feature?

I'm not sure if it is possible to achieve that with a plugin, but wouldn't that conflict with running projects, even if it was possible? Like, actually running your game would move the focus away from the editor window. And you'd probably want to keep tracking the time still.

**Comment by TackerTacker** [comment]
Hmmm, I see what you're saying. That is a good point, so it would probably be better if it wouldn't pause but instead track the time it is unfocused. But I guess there is no point to think about the best implementation if it's not achiveable with a plugin anyways, so I'll close the issue. 
Thank you for your quick answer and the cool plugin :+1:
