### ISSUE TITLE
Saving sessions

### ISSUE THREAD

**Issue by ignasKavaliauskas** [pycbouh/godot-time-tracker#3]
Hi, thank you for this plugin, it's really cool!

Is there a way to save your sessions? I couldn't find an option for that and after restarting Godot, all of my sessions are gone.
It would be nice to have the option to save your sessions and also specify where I want to save them!

**Comment by pycbouh** [comment]
Thank you!

Currently, there is no output from the plugin, but I was thinking about saving all the data in a file upon exit in case you forgot to check the timer before that. I guess it would make sense to restore them as well. I wonder if there is a file format already that I can use for that. If you have anything like that in your mind, please, let me know.

Regardless, I will look into this feature.

**Comment by ignasKavaliauskas** [comment]
Awesome, thanks!

My first thought would be using .ini files and the session name for the section. JSON would work too, might be also more convenient to work with in gdscript.
Upon exit sounds great, an additional small save button would be nice too I guess.

Looking forward to it!

**Comment by pycbouh** [comment]
Hey, sorry for the long wait, life kind of got in the way.

**New version 1.2.0 is now available!** I've added the automatic save/restore on editor start/close (or on plugin reload, for that matter), and also some intermediate autosaves when relevant data changes. I've also added a way to store current data to an arbitrary file and restore from it at will (overriding currently loaded data).

Incidentally, this allows to test various conditions easily without having to actually wait for some time or enter them manually every time. So a win for development as well.

Hope you like this new feature. You can get the new version from Github Releases, and will be pushing this new update for approval to the Asset Library shortly.
